### ISSUE TITLE
Caching classes and packages seen previously

### ISSUE THREAD

**Issue by vkazanov** [dakrone/emacs-java-imports#11]
I've noticed @dakrone added a TODO in the README: cache classes/packages seen in java-mode buffers and use the info for imports later.

I've been thinking about the feature for a while now. This would probably require a proper minor mode and a few hooks.

@dakrone , can you give some details about your vision of the feature? I may implement it in the following week or two, unless, of course, you want to do it yourself.

**Comment by dakrone** [comment]
@vkazanov whoops, I'm sorry I didn't see this earlier! I just added/implement this in 14c1e4144f667a3025b528411789ec1f20e163d9

**Comment by vkazanov** [comment]
@dakrone, oh, nice, this is better than I though it would be!
