### ISSUE TITLE
Preserve empty lines when inserting imports

### ISSUE THREAD

**Issue by vkazanov** [dakrone/emacs-java-imports#6]
See #5 where @dakrone notices a problem with preserving empty line.

This issue is just a placeholder for commits fixing the issue.

**Comment by vkazanov** [comment]
@dakrone it would be nice if you could check if the commit fixed the problem, and close the issue

Cheers!

**Comment by dakrone** [comment]
@vkazanov I'll check it out, thanks for adding it! (and thanks for adding tests!)

**Comment by dakrone** [comment]
I checked it out and I think it looks pretty good, thanks again! I also pushed another change fixing a bug with the sorted one and adding another test
