### ISSUE TITLE
Default packages for JDK classes 

### ISSUE THREAD

**Issue by vkazanov** [dakrone/emacs-java-imports#7]
A great deal of import declarations belongs to standard JDK classes, i.e. java.util.HashSet.

What I want to do is add a customizable map of classes to probable packages, and offer the package as a default in the function asking for a package name.

Example:

1. Try to import the `HashSet`.
2. No such name in the cache. Ask for a package name while offering a default `java.util` package if no input is given.
3. Insert `java.util.HashSet` into the file and save it into the package cache.

@dakrone what do you think?

**Comment by dakrone** [comment]
@vkazanov I think the idea sounds pretty solid! at worst even providing the standard Java Collections library would be probably 50% of the import statements I usually have to add

**Comment by vkazanov** [comment]
Great, I'll do it.

BTW, how often do you normally update the package in MELPA?

**Comment by vkazanov** [comment]
Done. 

@dakrone I've added the more popular packages from java.util.* I could think of. Could you take a look and see if there are any other useful ones..?

**Comment by dakrone** [comment]
I think those look great, we can always add more as we come across them! Closing this for now since you fixed it :)
